import assert from 'node:assert/strict';
import test from 'node:test';
import { addQuarterFreeThrows, buildQuarterEvents, calculateInteractiveGrade, reconcileQuarterRebounds, type ScheduledQuarterEvent } from '../src/utils/matchEvents';
import type { Attributes, PlayerProfile, Team } from '../src/types';
import { simulatePlayerMatchStats } from '../src/utils/leagueLogic';

function missedShot(index: number, type: 'user' | 'away'): ScheduledQuarterEvent {
  return {
    id: `miss-${index}`,
    quarter: 1,
    targetSeconds: 680 - index * 50,
    timeStr: '10:00',
    text: type === 'away' ? '对手强行攻筐受干扰偏出。' : '队友中投打铁。',
    type,
    userPtsDelta: 0,
    oppPtsDelta: 0,
    playerStatsDelta: { minutes: 0.5 },
  };
}

test('interactive games reconcile offensive and defensive rebound events to the simulation target', () => {
  const events = Array.from({ length: 10 }, (_, index) => missedShot(index, index % 2 ? 'away' : 'user'));
  reconcileQuarterRebounds(events, 1, 36, 4, '篮板中锋');

  assert.equal(events.reduce((sum, event) => sum + (event.playerStatsDelta?.reb || 0), 0), 4);
  assert.ok(events.some((event) => event.playerStatsDelta?.reb && event.text.includes('后场篮板')));
  assert.ok(events.some((event) => event.playerStatsDelta?.reb && event.text.includes('前场篮板')));
});

test('reconciliation preserves rebounds already generated by tactical events', () => {
  const events = [missedShot(0, 'away'), missedShot(1, 'user'), missedShot(2, 'away')];
  events[0].playerStatsDelta = { minutes: 0.5, reb: 1 };
  reconcileQuarterRebounds(events, 1, 36, 3, '篮板中锋');

  assert.equal(events.reduce((sum, event) => sum + (event.playerStatsDelta?.reb || 0), 0), 3);
});

test('free throws add points, makes and attempts to the same event', () => {
  const events = [missedShot(0, 'user')];
  addQuarterFreeThrows(events, 1, 36, 4, 3, '突破手');
  assert.equal(events[0].userPtsDelta, 3);
  assert.equal(events[0].playerStatsDelta?.pts, 3);
  assert.equal(events[0].playerStatsDelta?.ftm, 3);
  assert.equal(events[0].playerStatsDelta?.fta, 4);
});

test('game grade rewards all-around impact instead of points alone', () => {
  const grade = calculateInteractiveGrade({
    pts: 10, reb: 20, ast: 5, stl: 2, blk: 2, fgm: 4, fga: 9, ftm: 2, fta: 3, turnovers: 2,
  });
  assert.equal(grade, 'S');
});

test('a 99-rebounding starting center produces elite rebound totals in interactive games', () => {
  const attributes = Object.fromEntries([
    'midRange', 'threePoint', 'freeThrow', 'layup', 'dunk', 'insideFinish', 'postMove', 'ballHandle',
    'passing', 'perimeterDef', 'interiorDef', 'block', 'steal', 'rebounding', 'speed', 'vertical',
    'strength', 'stamina',
  ].map((key) => [key, key === 'rebounding' ? 99 : 80])) as unknown as Attributes;
  const player = {
    id: 'elite-center', name: '篮板中锋', jerseyNum: 50, height: '211', weight: '115', position: 'C',
    archetype: '篮板怪兽', attributes, attributeCaps: attributes, ovr: 92, currentTeamId: 'HOME',
  } as PlayerProfile;
  const makeTeam = (id: string): Team => ({
    id, name: id, city: id, abbrev: id, primaryColor: '#000', secondaryColor: '#fff', rating: 85,
    conference: 'West', starPlayer: '球星', wins: 0, losses: 0, roster: [],
  });
  const originalRandom = Math.random;
  let seed = 20260912;
  Math.random = () => ((seed = (seed * 1664525 + 1013904223) >>> 0) / 4294967296);
  try {
    let rebounds = 0;
    const games = 80;
    for (let game = 0; game < games; game += 1) {
      for (let quarter = 1; quarter <= 4; quarter += 1) {
        rebounds += buildQuarterEvents(quarter, makeTeam('HOME'), makeTeam('AWAY'), player, 36)
          .reduce((sum, event) => sum + (event.playerStatsDelta?.reb || 0), 0);
      }
    }
    const average = rebounds / games;
    assert.ok(average >= 10, `expected at least 10 RPG, received ${average}`);
    assert.ok(average <= 18, `expected no more than 18 RPG, received ${average}`);
  } finally {
    Math.random = originalRandom;
  }
});

test('interactive box-score categories stay in range of quick simulation', () => {
  const attributes = Object.fromEntries([
    'midRange', 'threePoint', 'freeThrow', 'layup', 'dunk', 'insideFinish', 'postMove', 'ballHandle',
    'passing', 'perimeterDef', 'interiorDef', 'block', 'steal', 'rebounding', 'speed', 'vertical',
    'strength', 'stamina',
  ].map((key) => [key, 90])) as unknown as Attributes;
  const player = {
    id: 'all-around-player', name: '全能球员', jerseyNum: 1, height: '203', weight: '105', position: 'SF',
    archetype: '全能核心', attributes, attributeCaps: attributes, ovr: 92, currentTeamId: 'HOME',
  } as PlayerProfile;
  const makeTeam = (id: string): Team => ({
    id, name: id, city: id, abbrev: id, primaryColor: '#000', secondaryColor: '#fff', rating: 85,
    conference: 'West', starPlayer: '球星', wins: 0, losses: 0, roster: [],
  });
  const totals = {
    interactive: { pts: 0, reb: 0, ast: 0, stl: 0, blk: 0, fta: 0 },
    quick: { pts: 0, reb: 0, ast: 0, stl: 0, blk: 0, fta: 0 },
  };
  const originalRandom = Math.random;
  let seed = 887766;
  Math.random = () => ((seed = (seed * 1664525 + 1013904223) >>> 0) / 4294967296);
  try {
    const games = 120;
    for (let game = 0; game < games; game += 1) {
      for (let quarter = 1; quarter <= 4; quarter += 1) {
        for (const event of buildQuarterEvents(quarter, makeTeam('HOME'), makeTeam('AWAY'), player, 36)) {
          const delta = event.playerStatsDelta;
          totals.interactive.pts += delta?.pts || 0;
          totals.interactive.reb += delta?.reb || 0;
          totals.interactive.ast += delta?.ast || 0;
          totals.interactive.stl += delta?.stl || 0;
          totals.interactive.blk += delta?.blk || 0;
          totals.interactive.fta += delta?.fta || 0;
        }
      }
      const quick = simulatePlayerMatchStats(player, 36);
      totals.quick.pts += quick.pts;
      totals.quick.reb += quick.reb;
      totals.quick.ast += quick.ast;
      totals.quick.stl += quick.stl;
      totals.quick.blk += quick.blk;
      totals.quick.fta += quick.fta;
    }
    for (const key of ['pts', 'reb', 'ast', 'stl', 'blk', 'fta'] as const) {
      const ratio = totals.interactive[key] / totals.quick[key];
      assert.ok(ratio >= 0.65 && ratio <= 1.45, `${key} parity ratio was ${ratio.toFixed(2)}`);
    }
  } finally {
    Math.random = originalRandom;
  }
});
