const http = require('http');
const zlib = require('zlib');
const tcb = require('@cloudbase/node-sdk');
const app = tcb.init({ env: process.env.CLOUDBASE_ENV_ID, accessKey: process.env.COLORBOX__ACCESS_KEY });
const rdb = app.rdb({ database: 'public' });
function path(req) { return new URL(req.url, 'http://localhost').pathname.replace(/^\/api/, '') || '/'; }
function rows(result) { return result?.data || result?.rows || []; }
function puid(req) { const raw = req.headers['x-cloudbase-context']; if (!raw) { const e = Error('请先登录'); e.statusCode = 401; throw e; } let data = Buffer.from(String(raw), 'base64'); if (data[0] === 31 && data[1] === 139) data = zlib.gunzipSync(data); const ctx = JSON.parse(data); const id = ctx.customUserId || ctx.userId || ctx.uid; if (!id) { const e = Error('请先登录'); e.statusCode = 401; throw e; } return String(id); }
function body(req) { return new Promise((resolve, reject) => { let data = ''; req.on('data', c => { data += c; if (data.length > 180000) reject(Error('请求过大')); }); req.on('end', () => { try { resolve(data ? JSON.parse(data) : {}); } catch { reject(Error('请求格式不正确')); } }); }); }
let cached = null; let cacheUntil = 0;
async function leaderboard() { if (cached && Date.now() < cacheUntil) return cached; cached = rows(await rdb.from('leaderboard_entries').select('id,display_name,score,record,updated_at').order('score', { ascending: false }).order('updated_at', { ascending: true }).order('id', { ascending: true }).limit(50)); cacheUntil = Date.now() + 5000; return cached; }
function send(res, status, data) { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Access-Control-Allow-Methods': 'GET, POST, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-CloudBase-Context' }); res.end(JSON.stringify(data)); }
http.createServer(async (req, res) => { if (req.method === 'OPTIONS') return send(res, 204, {}); try { const target = path(req); if (req.method === 'GET' && target === '/health') return send(res, 200, { code: 0, message: 'ok' }); if (req.method === 'GET' && target === '/leaderboard') return send(res, 200, { code: 0, message: 'success', data: await leaderboard() }); if (req.method === 'POST' && target === '/leaderboard/submit') { const input = await body(req); const score = Number(input.score); if (!Number.isSafeInteger(score) || score < 0 || score > 2147483647 || !input.record || typeof input.record !== 'object') { const e = Error('传奇记录格式不正确'); e.statusCode = 400; throw e; } const id = puid(req); const existing = rows(await rdb.from('leaderboard_entries').select('score').eq('puid', id).limit(1))[0]; if (!existing) await rdb.from('leaderboard_entries').insert([{ puid: id, display_name: String(input.displayName || '传奇球员').slice(0, 40), score, record: input.record }]); else if (score > Number(existing.score)) await rdb.from('leaderboard_entries').update({ display_name: String(input.displayName || '传奇球员').slice(0, 40), score, record: input.record, updated_at: new Date().toISOString() }).eq('puid', id); cached = null; return send(res, 200, { code: 0, message: 'success' }); } return send(res, 404, { code: 404, message: 'not found' }); } catch (error) { return send(res, error.statusCode || 500, { code: error.statusCode || 500, message: error.statusCode ? error.message : '服务暂时不可用' }); } }).listen(process.env.PORT || 9000);
